name: schedule_by_miniute
on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: loop_write_tt
        with: 
          token: ${{secrets.zhangxianzhuo}}
        run: date +%s >> tt
