name: schedule_by_miniute
on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v2
        with: 
          token: ${{secrets.auto_write}}
      - name: write_to_file
        run: date +%s >> tt
