name: schedule_by_miniute
on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v2

      - name: write_to_file
        run: |
          date +%s >> tt
          git add tt
          git commit -m "add file tt"
          git push
        
