name: timezone-and-schedule

on:
  # workflow_dispatch:
  schedule:
    - cron: '18 11 * * *'

jobs:
  show_data:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        run: actions/checkout@v4
      - name: set timezone
        run: sudo timedatectl set-timezone Asia/Shanghai
      - name: show current day
        run: date +%F_%H:%M:%S
    
