name: timezone-and-schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '37 10 18 * *'

jobs:
  show_data:
    runs-on: [ubuntu-latest]
    steps:
      - name: set timezone
        run: sudo timedatectl set-timezone Asia/Shanghai
      - name: show current day
        run: date +%F_%H:%M:%S
    
