name: timezone-and-schedule

on:
  # workflow_dispatch:
  schedule:
    - cron: '49 4 * * *'

jobs:
  show_data:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: show current day
        # run: date +%F_%H:%M:%S
        run: date -u
    
